kind: pipeline
name: jsql-docs-ci

clone:
  disable: true

steps:
- name: pull-docs-source
  image: docker:git
  volumes:
  - name: jsql-gitbook-source
    path: /home/gitbook/jsql
  volumes:
  - name: ssh
    path: /root/.ssh
  commands:
  - cd /home/gitbook/jsql
  - git pull --rebase

volumes:
- name: jsql-gitbook-source
  host:
    path: /home/gitbook/jsql
volumes:
- name: ssh
  host:
    path: /root/.ssh

trigger:
  branch:
  - master
  event:
  - push
  - pull_request